name: skyhook
description: Website for skyhook

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  http: 0.13.4
  url_launcher: ^6.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

